# Generated by Django 3.1.3 on 2023-07-15 17:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.gen_code, max_length=8, unique=True),
        ),
    ]
